version: '3.9'
services:
  api:
    build:
      context: .
      target: app
    image: postboard-api
    container_name: postboard-api-1
    env_file:
      - .env
    restart: always
    volumes:
      - ./app:/app/app
    ports:
      - ${UVICORN_PORT}:${UVICORN_PORT}
    depends_on:
      postgres:
        condition: service_healthy
  test:
    build:
      context: .
      target: test
    image: postboard-api-test
    container_name: postboard-api-test-1
    command: ["tail", "-f", "/dev/null"]
    env_file:
      - .env.test
    volumes:
      - ./coverage_report:/app/coverage_report
    depends_on:
      postgres:
        condition: service_healthy