version: '3.9'
services:
  api:
    build: .
    container_name: postboard_api
    env_file:
      - .env
    restart: always
    volumes:
      - ./app:/usr/src/postboard/app
      - ./pyproject.toml:/usr/src/postboard/pyproject.toml
      - ./poetry.lock:/usr/src/postboard/poetry.lock
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy