version: '3.9'
services:
  postgres:
    image: postgres:13.5
    container_name: postboard_postgres
    environment:
        - POSTGRES_USER=postboard
        - POSTGRES_PASSWORD=postboard
        - POSTGRES_DB=postboard
    volumes:
        - postgres-data:/var/lib/postgresql/data
    ports:
        - 5432:5432

volumes:
  postgres-data: